openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 0.1.9
servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
paths:
  /api/jobType:
    post:
      summary: Create a new job type.
      description: Create a new job type.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/JobType'
      responses:
        '200':    # status code
          description: Model Job Type
          content:
            application/json:
              schema: 
                $ref: '#components/schemas/JobType'
    get:
      summary: Get all job types
      description: Get all job types
      responses:
        '200':
          description: Array of Job Types
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#components/schemas/JobType'
  /api/job:
    post:
      summary: Create a new job
      description: Create a new job
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#components/schemas/Job'
      responses:
        '200':
          description: Model Job
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Job'
    #get:
components:
  schemas:
    UserRequest:
      type: object
      properties:
        id:
          type: number
        email:
          type: string
        name:
          type: string
        password:
          type: string

    EmployeeRequest:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        userId:
          type: number
        jobId:
          type: number
        branchOfficeId:
          type: number
        salary:
          type: number
        isActive:
          type: boolean

    JobTypeRequest:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        description:
          type: string

    JobRequest:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        description:
          type: string
        jobTypeId:
          type: number
        baseSalary:
          type: number

    OrderStatusRequest:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        description:
          type: string

    OrderRequest:
      type: object
      properties:
        id:
          type: number
        date:
          type: string
          format: date-time
        total:
          type: number
        email:
          type: string
        client:
          type: string
        address:
          type: string
        phone:
          type: string
        description:
          type: string
        orderStatusId:
          type: number

    PackageRequest:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        weight:
          type: number
        cost:
          type: number
        total:
          type: number
        hight:
          type: number
        widht:
          type: number
        orderId:
          type: number

    BranchOfficeRequest:
      type: object
      properties:
        id:
          type: number
        address:
          type: string
        isActive:
          type: boolean
        cityId:
          type: number

    CityRequest:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        departmentId:
          type: number

    DepartmentRequest:
      type: object
      properties:
        id:
          type: number
        name:
          type: string

    PathRequest:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        routeId:
          type: number
        originId:
          type: number
        destinationId:
          type: number

    RouteRequest:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        priceWeight:
          type: number
        originId:
          type: number
        destinationId:
          type: number
        isActive:
          type: boolean
